name: myapp
description: "Raqib - Smart app to save and manage your favorite locations"
publish_to: 'none'

version: 2.0.0+3

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio_cache_interceptor: ^4.0.0
  flutter_map: ^7.0.2
  flutter_map_cache: ^2.1.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.0
  connectivity_plus: ^6.1.5
  shimmer: ^3.0.0
  http: ^1.2.2
  http_cache_hive_store: ^5.0.1
  path_provider: ^2.1.5
  package_info_plus: ^8.0.2
  open_filex: ^4.5.0
  flutter_markdown: ^0.7.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: lib/assets/fonts/cairo.ttf

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/images/ic_launcher.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/images/ic_launcher.png"
